{
 "title": "global",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "hide_rooms",
    "label": "Hide rooms",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: v.defaultBucket, tag: \"room\")\n"
   }
  ]
 },
 "panels": [
  {
   "title": "temperature gauge",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"temperature\" and not contains(value:r.room, set:${hide_rooms:json}))"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"temperature\" and r.room != \"bathroom\" and not contains(value:r.room, set:${hide_rooms:json}))\n  |> group(columns: [\"room\", \"_time\"])\n  |> mean()\n  |> group(columns: [\"room\"])"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"humidity\" and not contains(value:r.room, set:${hide_rooms:json}) )\n  |> group(columns: [\"room\", \"_time\"])\n  |> mean()\n  |> group(columns: [\"room\"])"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"raw\" )"
    }
   ]
  },
  {
   "title": "pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pressure\" and not contains(value:r.room, set:${hide_rooms:json}) )"
    }
   ]
  },
  {
   "title": "power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"hp\" )\n  |> difference()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"hc\" )\n  |> difference()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\" )\n  |> map(fn: (r) => ({r with _value: r._value / 60.0}))"
    }
   ]
  }
 ]
}