#!/bin/bash
# @parseArger-begin
# @parseArger-help "Build station filesystem" --option "help" --short-option "h"
# @parseArger-verbose --option "verbose" --level "0"
# @parseArger-declarations
# @parseArger opt js "path to js file, ':' to separate target directory (/assets/js by default)" --short j --repeat --complete file
# @parseArger opt css "path to css file, ':' to separate target directory (/assets/css by default)" --short c --repeat --complete file
# @parseArger opt directory "additional directory path, all files will be gzipped, ':' to separate target directory (/ by default)" --short d --repeat --complete directory
# @parseArger opt file "file to add, will be gzipped, ':' to separate target directory (/ by default)" --short f --repeat  --complete file
# @parseArger opt file-no-gz "add a file without gzip, ':' to separate target directory (/ by default)" --short F --repeat  --complete file
# @parseArger opt node "node executable" --default-value "node"
# @parseArger opt pio "pio executable" --default-value "/home/didi/.platformio/penv/bin/pio"
# @parseArger opt environement "build environment" --short e --default-value "nodemcuv2"
# @parseArger opt upload "station to upload to, will set --environment" --short u --complete-custom "if [ -d stations/.stations ]; then /usr/bin/ls stations/.stations ;fi"
# @parseArger flag dry "do not upload (just build for a station)" --short D
# @parseArger-declarations-end

# @parseArger-utils
_helpHasBeenPrinted=1;
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
# @parseArger-utils-end

# @parseArger-parsing
die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	log "$1" -3 >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options=''
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# POSITIONALS ARGUMENTS
_positionals=();
# OPTIONALS ARGUMENTS
_arg_js=()
_arg_css=()
_arg_directory=()
_arg_file=()
_arg_file_no_gz=()
_arg_node="node"
_arg_pio="/home/didi/.platformio/penv/bin/pio"
_arg_environement="nodemcuv2"
_arg_upload=
# FLAGS
_arg_dry="off"
_verbose_level="0";



print_help()
{
	_triggerSCHelp=1;

	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
		_helpHasBeenPrinted=0;
		echo -e "Build station filesystem:"
	echo -e "	-j, --js <js>: path to js file, ':' to separate target directory (/assets/js by default), repeatable"
	echo -e "	-c, --css <css>: path to css file, ':' to separate target directory (/assets/css by default), repeatable"
	echo -e "	-d, --directory <directory>: additional directory path, all files will be gzipped, ':' to separate target directory (/ by default), repeatable"
	echo -e "	-f, --file <file>: file to add, will be gzipped, ':' to separate target directory (/ by default), repeatable"
	echo -e "	-F, --file-no-gz <file-no-gz>: add a file without gzip, ':' to separate target directory (/ by default), repeatable"
	echo -e "	--node <node>: node executable [default: ' node ']"
	echo -e "	--pio <pio>: pio executable [default: ' /home/didi/.platformio/penv/bin/pio ']"
	echo -e "	-e, --environement <environement>: build environment [default: ' nodemcuv2 ']"
	echo -e "	-u, --upload <upload>: station to upload to, will set --environment"
	echo -e "	-D|--dry|--no-dry: do not upload (just build for a station)"
	echo -e "Usage :
	$0 [--js <value>] [--css <value>] [--directory <value>] [--file <value>] [--file-no-gz <value>] [--node <value>] [--pio <value>] [--environement <value>] [--upload <value>] [--[no-]dry]";
	fi

}

log() {
	local _arg_msg="${1}";
	local _arg_level="${2:"0"}";
	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
		case "$_arg_level" in
			-3)
				_arg_COLOR="\033[0;31m";
				;;
			-2)
				_arg_COLOR="\033[0;33m";
				;;
			-1)
				_arg_COLOR="\033[1;33m";
				;;
			1)
				_arg_COLOR="\033[0;32m";
				;;
			2)
				_arg_COLOR="\033[1;36m";
				;;
			3)
				_arg_COLOR="\033[0;36m";
				;;
			*)
				_arg_COLOR="\033[0m";
				;;
		esac
		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
	fi
}

parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-j|--js)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_js+=("$2")
				shift
				;;
			--js=*)
				_arg_js+=("${_key##--js=}")
				;;
			-j*)
				_arg_js+=("${_key##-j}")
				;;
			
			-c|--css)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_css+=("$2")
				shift
				;;
			--css=*)
				_arg_css+=("${_key##--css=}")
				;;
			-c*)
				_arg_css+=("${_key##-c}")
				;;
			
			-d|--directory)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_directory+=("$2")
				shift
				;;
			--directory=*)
				_arg_directory+=("${_key##--directory=}")
				;;
			-d*)
				_arg_directory+=("${_key##-d}")
				;;
			
			-f|--file)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_file+=("$2")
				shift
				;;
			--file=*)
				_arg_file+=("${_key##--file=}")
				;;
			-f*)
				_arg_file+=("${_key##-f}")
				;;
			
			-F|--file-no-gz)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_file_no_gz+=("$2")
				shift
				;;
			--file-no-gz=*)
				_arg_file_no_gz+=("${_key##--file-no-gz=}")
				;;
			-F*)
				_arg_file_no_gz+=("${_key##-F}")
				;;
			
			--node)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_node="$2"
				shift
				;;
			--node=*)
				_arg_node="${_key##--node=}"
				;;
			
			--pio)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_pio="$2"
				shift
				;;
			--pio=*)
				_arg_pio="${_key##--pio=}"
				;;
			
			-e|--environement)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_environement="$2"
				shift
				;;
			--environement=*)
				_arg_environement="${_key##--environement=}"
				;;
			-e*)
				_arg_environement="${_key##-e}"
				;;
			
			-u|--upload)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_upload="$2"
				shift
				;;
			--upload=*)
				_arg_upload="${_key##--upload=}"
				;;
			-u*)
				_arg_upload="${_key##-u}"
				;;
			
			-D|--dry)
				_arg_dry="on"
				;;
			--no-dry)
				_arg_dry="off"
				;;
			-h|--help)
				print_help;
				exit 0;
				;;
			-h*)
				print_help;
				exit 0;
				;;
			-v|--version)
				print_version;
				exit 0;
				;;
			-v*)
				print_version;
				exit 0;
				;;
			--verbose)
				if [ $# -lt 2 ];then
					_verbose_level="$((_verbose_level + 1))";
				else
					_verbose_level="$2";
					shift;
				fi
				;;
			
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string=""
	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
	fi
	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}.
	${_positionals[*]}" 1;
	fi
}


assign_positional_args()
{
	local _positional_name _shift_for=$1;
	_positional_names="";
	shift "$_shift_for"
	for _positional_name in ${_positional_names};do
		test $# -gt 0 || break;
		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
		shift;
	done
}

print_debug()
{
	print_help
	# shellcheck disable=SC2145
	echo "DEBUG: $0 $@";
	
	echo -e "\tjs: ${_arg_js[*]}";
	echo -e "\tcss: ${_arg_css[*]}";
	echo -e "\tdirectory: ${_arg_directory[*]}";
	echo -e "\tfile: ${_arg_file[*]}";
	echo -e "\tfile-no-gz: ${_arg_file_no_gz[*]}";
	echo -e "\tnode: ${_arg_node}";
	echo -e "\tpio: ${_arg_pio}";
	echo -e "\tenvironement: ${_arg_environement}";
	echo -e "\tupload: ${_arg_upload}";
	echo -e "\tdry: ${_arg_dry}";

}

print_version()
{
	echo "";
}

on_interrupt() {
	die Process aborted! 130;
}

parse_commandline "$@";
handle_passed_args_count;
assign_positional_args 1 "${_positionals[@]}";
trap on_interrupt INT;



# @parseArger-parsing-end
# print_debug "$@"
# @parseArger-end

# shellcheck source=common
source "$_SCRIPT_DIR/common";
# shellcheck source="../stations/stations"
source "./stations/stations";

# a station has been defined
if [ "$_arg_upload" != "" ] && station_exists "${_arg_upload}"; then
	# shellcheck source=./export-conf
	source "$STATIONIO_DIR/utils/export-conf" "${_arg_upload}";
	
	# check if station has bee loaded
	# shellcheck disable=SC2154
	if [ "$stationIOip" == "" ]; then
		die "Station ${_arg_upload} has no ip";
	fi
	# set station board as env
	_arg_environement="${stationIOboard}";
	
	# check station sensors for js and css files to add for upload
	for _sensor in "${stationIOsensors[@]}"; do
		if [ -f "$STATIONIO_DIR/src/sensors/${_sensor}.js" ]; then
			_arg_js+=("$STATIONIO_DIR/src/sensors/${_sensor}.js:");
		fi
		if [ -f "$STATIONIO_DIR/src/sensors/${_sensor}.css" ]; then
			_arg_css+=("$STATIONIO_DIR/src/sensors/${_sensor}.css:");
		fi
	done

	# add station static files and directories
	if [ "${#stationIOfiles[@]}" -gt 0 ]; then
		_arg_file=("${stationIOfiles[@]}" "${_arg_file[@]}");
	fi
	if [ "${#stationIOdirectories[@]}" -gt 0 ]; then
		_arg_directory=("${stationIOdirectories[@]}" "${_arg_directory[@]}");
	fi
fi

rm -rf data;
mkdir data;

gzip_files() {
  src_dir=$1;
  dest_dir=$2;

  for dir in "$src_dir"/*; do
    if [ -d "$dir" ]; then
      subdir=$(basename "$dir");
      mkdir -p "$dest_dir/$subdir";
      (gzip_files "$dir" "$dest_dir/$subdir");
    elif [ -f "$dir" ]; then
      filename=$(basename "$dir");
			if [[ "$filename" == *.js ]] || [[ "$filename" == *.css ]]; then
				"$_arg_node" "$STATIONIO_DIR/node_modules/.bin/minify" "$dir" | gzip -c - > "$dest_dir/$filename.gz";
			else
				gzip "$dir" -c > "$dest_dir/$filename.gz";
			fi
    fi
  done
}

gzip_files "$STATIONIO_DIR/src/assets" "$STATIONIO_DIR/data/assets"

for file in "${_arg_file[@]}"; do
	cpt="";
	if [[ "$file" == *:* ]]; then
		cpt="${file##*:}";
		file="${file%%:*}";
	fi
	if [ "$cpt" != "" ]; then
		cpt+="/";
	fi
	if [ ! -d "$STATIONIO_DIR/data/$cpt" ]; then
		mkdir -p "$STATIONIO_DIR/data/$cpt";
	fi

	(gzip "$file" -c > "$STATIONIO_DIR/data/$cpt$(basename "$file").gz");
done

for dir2add in "${_arg_directory[@]}"; do
	cpt="";
	if [[ "$dir2add" == *:* ]]; then
		cpt="${dir2add##*:}";
		dir2add="${dir2add%%:*}";
	fi
	if [ "$cpt" != "" ]; then
		cpt+="/";
	fi
	if [ ! -d "data$STATIONIO_DIR//$cpt" ]; then
		mkdir -p "data$STATIONIO_DIR//$cpt";
	fi

	(gzip_files "$dir2add" "data$STATIONIO_DIR//$cpt$dir2add");
done

for file in "${_arg_file_no_gz[@]}"; do
	cpt="";
	if [[ "$file" == *:* ]]; then
		cpt="${file##*:}";
		file="${file%%:*}";
	fi
	if [ "$cpt" != "" ]; then
		cpt+="/";
	fi
	if [ ! -d "data$STATIONIO_DIR//$cpt" ]; then
		mkdir -p "data$STATIONIO_DIR//$cpt";
	fi

	cp "$file" "data$STATIONIO_DIR//$(basename "$file")";
done

for js in "${_arg_js[@]}"; do
	cpt="";
	if [[ "$js" == *:* ]]; then
		cpt="${js##*:}";
		js="${js%%:*}";
	fi
	if [ "$cpt" != "" ]; then
		cpt+="/";
	fi
	if [ ! -d "$STATIONIO_DIR/data/assets/js/$cpt" ]; then
		mkdir -p "$STATIONIO_DIR/data/assets/js/$cpt";
	fi

	"$_arg_node" "$STATIONIO_DIR/node_modules/.bin/minify" "$js" | gzip -c - > "$STATIONIO_DIR/data/assets/js/$cpt$(basename "$js").gz";
done

for css in "${_arg_css[@]}"; do
	cpt="";
	if [[ "$css" == *:* ]]; then
		cpt="${css##*:}";
		css="${css%%:*}";
	fi
	if [ "$cpt" != "" ]; then
		cpt+="/";
	fi
	if [ ! -d "$STATIONIO_DIR/data/assets/css/$cpt" ]; then
		mkdir -p "$STATIONIO_DIR/data/assets/css/$cpt";
	fi

	"$_arg_node" "$STATIONIO_DIR/node_modules/.bin/minify" "$css" | gzip -c - > "$STATIONIO_DIR/data/assets/css/$(basename "$css").gz";
done

"$_arg_pio" run -t buildfs -e "$_arg_environement";

if [ "$_arg_upload" != "" ] && [ "$_arg_dry" != "on" ]; then
	"$STATIONIO_DIR/utils/upload" "$_arg_upload" --fs;
fi
