#!/bin/bash
# @parseArger-begin
# @parseArger-help "Set station configuration" --option "help" --short-option "h"
# @parseArger-verbose --option "verbose" --level "0"
# @parseArger-declarations
# @parseArger pos name "station name"
# @parseArger opt sensor "sensor to add" --short s --repeat
# @parseArger opt ip "ip address" --short i --default-value "0"
# @parseArger opt board "pio env" --short b --default-value "nodemcuv2"
# @parseArger opt data-file "data-file to add" --short f --repeat
# @parseArger opt data-directory "data-directory to add" --short d --repeat
# @parseArger opt js "js to add" --short j --repeat
# @parseArger opt css "css to add" --short c --repeat
# @parseArger-declarations-end

# @parseArger-utils
_helpHasBeenPrinted=1;
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
# @parseArger-utils-end

# @parseArger-parsing
die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	log "$1" -3 >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options=''
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# POSITIONALS ARGUMENTS
_positionals=();
_arg_name="";
# OPTIONALS ARGUMENTS
_arg_sensor=()
_arg_ip="0"
_arg_board="nodemcuv2"
_arg_data_file=()
_arg_data_directory=()
_arg_js=()
_arg_css=()
# FLAGS
_verbose_level="0";



print_help()
{
	_triggerSCHelp=1;

	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
		_helpHasBeenPrinted=0;
		echo -e "Set station configuration:"
	echo -e "	name: station name"
	echo -e "	-s, --sensor <sensor>: sensor to add, repeatable"
	echo -e "	-i, --ip <ip>: ip address [default: ' 0 ']"
	echo -e "	-b, --board <board>: pio env [default: ' nodemcuv2 ']"
	echo -e "	-f, --data-file <data-file>: data-file to add, repeatable"
	echo -e "	-d, --data-directory <data-directory>: data-directory to add, repeatable"
	echo -e "	-j, --js <js>: js to add, repeatable"
	echo -e "	-c, --css <css>: css to add, repeatable"
	echo -e "Usage :
	$0 <name> [--sensor <value>] [--ip <value>] [--board <value>] [--data-file <value>] [--data-directory <value>] [--js <value>] [--css <value>]";
	fi

}

log() {
	local _arg_msg="${1}";
	local _arg_level="${2:"0"}";
	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
		case "$_arg_level" in
			-3)
				_arg_COLOR="\033[0;31m";
				;;
			-2)
				_arg_COLOR="\033[0;33m";
				;;
			-1)
				_arg_COLOR="\033[1;33m";
				;;
			1)
				_arg_COLOR="\033[0;32m";
				;;
			2)
				_arg_COLOR="\033[1;36m";
				;;
			3)
				_arg_COLOR="\033[0;36m";
				;;
			*)
				_arg_COLOR="\033[0m";
				;;
		esac
		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
	fi
}

parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-s|--sensor)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_sensor+=("$2")
				shift
				;;
			--sensor=*)
				_arg_sensor+=("${_key##--sensor=}")
				;;
			-s*)
				_arg_sensor+=("${_key##-s}")
				;;
			
			-i|--ip)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_ip="$2"
				shift
				;;
			--ip=*)
				_arg_ip="${_key##--ip=}"
				;;
			-i*)
				_arg_ip="${_key##-i}"
				;;
			
			-b|--board)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_board="$2"
				shift
				;;
			--board=*)
				_arg_board="${_key##--board=}"
				;;
			-b*)
				_arg_board="${_key##-b}"
				;;
			
			-f|--data-file)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_data_file+=("$2")
				shift
				;;
			--data-file=*)
				_arg_data_file+=("${_key##--data-file=}")
				;;
			-f*)
				_arg_data_file+=("${_key##-f}")
				;;
			
			-d|--data-directory)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_data_directory+=("$2")
				shift
				;;
			--data-directory=*)
				_arg_data_directory+=("${_key##--data-directory=}")
				;;
			-d*)
				_arg_data_directory+=("${_key##-d}")
				;;
			
			-j|--js)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_js+=("$2")
				shift
				;;
			--js=*)
				_arg_js+=("${_key##--js=}")
				;;
			-j*)
				_arg_js+=("${_key##-j}")
				;;
			
			-c|--css)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_css+=("$2")
				shift
				;;
			--css=*)
				_arg_css+=("${_key##--css=}")
				;;
			-c*)
				_arg_css+=("${_key##-c}")
				;;
			
			-h|--help)
				print_help;
				exit 0;
				;;
			-h*)
				print_help;
				exit 0;
				;;
			-v|--version)
				print_version;
				exit 0;
				;;
			-v*)
				print_version;
				exit 0;
				;;
			--verbose)
				if [ $# -lt 2 ];then
					_verbose_level="$((_verbose_level + 1))";
				else
					_verbose_level="$2";
					shift;
				fi
				;;
			
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="name"
	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
	fi
	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
	${_positionals[*]}" 1;
	fi
}


assign_positional_args()
{
	local _positional_name _shift_for=$1;
	_positional_names="_arg_name ";
	shift "$_shift_for"
	for _positional_name in ${_positional_names};do
		test $# -gt 0 || break;
		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
		shift;
	done
}

print_debug()
{
	print_help
	# shellcheck disable=SC2145
	echo "DEBUG: $0 $@";
	
	echo -e "\tname: ${_arg_name}";
	echo -e "\tsensor: ${_arg_sensor[*]}";
	echo -e "\tip: ${_arg_ip}";
	echo -e "\tboard: ${_arg_board}";
	echo -e "\tdata-file: ${_arg_data_file[*]}";
	echo -e "\tdata-directory: ${_arg_data_directory[*]}";
	echo -e "\tjs: ${_arg_js[*]}";
	echo -e "\tcss: ${_arg_css[*]}";

}

print_version()
{
	echo "";
}

on_interrupt() {
	die Process aborted! 130;
}

parse_commandline "$@";
handle_passed_args_count;
assign_positional_args 1 "${_positionals[@]}";
trap on_interrupt INT;



# @parseArger-parsing-end
# print_debug "$@"
# @parseArger-end

if [ ! -d "./stations/.stations" ]; then
	mkdir "./stations/.stations";
fi

# shellcheck source=./exportStationConf
source "utils/exportStationConf" "${_arg_name}";

if [ "$stationIOip" == "" ]; then
	stationIOip="0"
	stationIOboard="nodemcuv2"
	stationIOsensors=()
	stationIOjs=()
	stationIOcss=()
	stationIOfiles=()
	stationIOdirectories=()
fi

if [ "$_arg_ip" != "" ]; then
	if [ "$stationIOip" != "" ] && [ "$_arg_ip" == 0 ]; then
		_arg_ip="$stationIOip";
	fi
	stationIOip="${_arg_ip}";
fi

if [ "$_arg_board" != "" ]; then
	stationIOboard="${_arg_board}";
fi

if [ "${#_arg_sensor[@]}" -gt 0 ]; then
	stationIOsensors=("${_arg_sensor[@]}");
fi

if [ "${#_arg_js[@]}" -gt 0 ]; then
	stationIOjs=("${_arg_js[@]}");
fi

if [ "${#_arg_css[@]}" -gt 0 ]; then
	stationIOcss=("${_arg_css[@]}");
fi

if [ "${#_arg_data_file[@]}" -gt 0 ]; then
	stationIOfiles=("${_arg_data_file[@]}");
fi

if [ "${#_arg_data_directory[@]}" -gt 0 ]; then
	stationIOdirectories=("${_arg_data_directory[@]}");
fi

echo -e "# StationIO configuration for ${_arg_name} station" > "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_ip=\"${stationIOip}\"" >> "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_board=\"${stationIOboard}\"" >> "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_sensors=( $(out=""; for sen in "${stationIOsensors[@]}";do out+=" \"$sen\""; done; echo "$out"; ) )" >> "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_js=( $(out=""; for sen in "${stationIOjs[@]}";do out+=" \"$sen\""; done; echo "$out"; ) )" >> "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_css=( $(out=""; for sen in "${stationIOcss[@]}";do out+=" \"$sen\""; done; echo "$out"; ) )" >> "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_files=( $(out=""; for sen in "${stationIOfiles[@]}";do out+=" \"$sen\""; done; echo "$out"; ) )" >> "stations/.stations/${_arg_name}";
echo -e "${_arg_name}_directories=( $(out=""; for sen in "${stationIOdirectories[@]}";do out+=" \"$sen\""; done; echo "$out"; ) )" >> "stations/.stations/${_arg_name}";
